import {FileHelper} from "../helpers/file-helper";
import {StringHelper} from "../helpers/string-helper";
import {filesystem} from "gluegun";

const fs = require('fs');

export class ClassCodeGenerator {

    public generateClass(folder: string, className: string, innerRows: string[], headRows?: string[]) {
        FileHelper.createFolderIfNotExists(folder);

        if (!headRows)
            headRows = [];

        const rows = [
            '/* generated by acady */',
            ...headRows,
            ``,
            `export class ${className} {`,
        ];

        innerRows.forEach(row => rows.push(row));

        rows.push('}');

        const code = rows.join(filesystem.eol);

        fs.writeFileSync(FileHelper.path([folder, this.getClassFilename(className) + '.ts']), code);
    }

    public getClassFilename(className: string) {
        return StringHelper.camelToKebab(StringHelper.lowerFirstLetter(className));
    }
}
