import {FileHelper} from "../helpers/file-helper";
import {StringHelper} from "../helpers/string-helper";
import {filesystem} from "gluegun";

const fs = require('fs');

export class ClassCodeGenerator {
    public static generateClass(folder: string, className: string, innerRows: string[]) {
        FileHelper.createFolderIfNotExists(folder);

        const rows = [
            '/* generated by acady */',
            `export class ${className} {`,
        ];

        innerRows.forEach(row => rows.push(row));

        rows.push('}');

        const fileName = StringHelper.camelToKebab(StringHelper.lowerFirstLetter(className)) + '.ts';
        const code = rows.join(filesystem.eol);

        fs.writeFileSync(FileHelper.path([folder, fileName]), code);
    }
}
